"""align ticket schema

Revision ID: 7b07068c7bb2
Revises: 
Create Date: 2026-09-14 23:38:41.132757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b07068c7bb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # Add new columns temporarily as nullable
    op.add_column(
        "tickets",
        sa.Column(
            "assigned_agent_id",
            sa.UUID(),
            nullable=True
        )
    )

    op.add_column(
        "tickets",
        sa.Column(
            "original_message",
            sa.Text(),
            nullable=True
        )
    )

    op.add_column(
        "tickets",
        sa.Column(
            "priority",
            sa.String(),
            nullable=True
        )
    )

    op.add_column(
        "tickets",
        sa.Column(
            "channel",
            sa.String(),
            nullable=True
        )
    )

    # Move existing data into the new structure
    op.execute(
        """
        UPDATE tickets
        SET
            original_message = message,
            priority = 'normal',
            channel = 'web_form'
        """
    )

    # Now that every existing row has values,
    # make the new columns required.
    op.alter_column(
        "tickets",
        "original_message",
        nullable=False
    )

    op.alter_column(
        "tickets",
        "priority",
        nullable=False
    )

    op.alter_column(
        "tickets",
        "channel",
        nullable=False
    )

    # Rename the old agent relationship
    op.drop_constraint(
        op.f("tickets_agent_id_fkey"),
        "tickets",
        type_="foreignkey"
    )

    op.create_foreign_key(
        "tickets_assigned_agent_id_fkey",
        "tickets",
        "agents",
        ["assigned_agent_id"],
        ["id"]
    )

    # Remove fields replaced by the new ticket structure
    op.drop_column("tickets", "responded_at")
    op.drop_column("tickets", "message")
    op.drop_column("tickets", "agent_id")
    op.drop_column("tickets", "response")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_agent_id_fkey'), 'tickets', 'agents', ['agent_id'], ['id'])
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('tickets', 'subject',
               existing_type=sa.String(length=160),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('tickets', 'channel')
    op.drop_column('tickets', 'priority')
    op.drop_column('tickets', 'original_message')
    op.drop_column('tickets', 'assigned_agent_id')
    op.alter_column('docs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('docs', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('customers', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customers', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agents', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'agent'::text"))
    op.alter_column('agents', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agents', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agents', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
